### ISSUE TITLE
go test fails with segfault

### ISSUE THREAD

**Issue by flimzy** [BenLubar/espeak#2]
The following executed from my `$GOPATH/src/gopkg.in/BenLubar/espeak.v2` on a Debian 9.4 system:

    $ sudo aptitude install libespeak-ng-dev
    The following NEW packages will be installed:
      libespeak-ng-dev 
    0 packages upgraded, 1 newly installed, 0 to remove and 1 not upgraded.
    Need to get 200 kB of archives. After unpacking 701 kB will be used.
    Get: 1 http://ftp.nl.debian.org/debian stretch/main amd64 libespeak-ng-dev amd64 1.49.0+dfsg-11 [200 kB]
    Fetched 200 kB in 0s (504 kB/s)          
    Selecting previously unselected package libespeak-ng-dev:amd64.
    (Reading database ... 247375 files and directories currently installed.)
    Preparing to unpack .../libespeak-ng-dev_1.49.0+dfsg-11_amd64.deb ...
    Unpacking libespeak-ng-dev:amd64 (1.49.0+dfsg-11) ...
    Setting up libespeak-ng-dev:amd64 (1.49.0+dfsg-11) ...
    $ go test ./...
    fatal error: unexpected signal during runtime execution
    [signal SIGSEGV: segmentation violation code=0x1 addr=0x108 pc=0x7fd5df82795b]

    runtime stack:
    runtime.throw(0x53fe8a, 0x2a)
            /usr/local/go/src/runtime/panic.go:616 +0x81
    runtime.sigpanic()
            /usr/local/go/src/runtime/signal_unix.go:372 +0x28e

    goroutine 1 [syscall]:
    runtime.cgocall(0x4eed90, 0xc42005db10, 0xc420000100)
            /usr/local/go/src/runtime/cgocall.go:128 +0x64 fp=0xc42005dac0 sp=0xc42005da88 pc=0x4034e4
    gopkg.in/BenLubar/espeak%2ev2._Cfunc_espeak_ng_Synthesize(0x15877b0, 0x0, 0x100000000, 0x1100000000, 0x0, 0x0, 0xc400000000)
            _cgo_gotypes.go:374 +0x50 fp=0xc42005db10 sp=0xc42005dac0 pc=0x4ec1d0
    gopkg.in/BenLubar/espeak%2ev2.synthesize.func3(0x15877b0, 0x0, 0x100000000, 0x1100000000, 0x0, 0x0, 0x0)
            /home/jonhall/go/src/gopkg.in/BenLubar/espeak.v2/native.go:280 +0x98 fp=0xc42005db58 sp=0xc42005db10 pc=0x4edde8
    gopkg.in/BenLubar/espeak%2ev2.synthesize(0x5415af, 0x45a, 0xc4200aa080, 0x0, 0x0)
            /home/jonhall/go/src/gopkg.in/BenLubar/espeak.v2/native.go:280 +0xde fp=0xc42005dba8 sp=0xc42005db58 pc=0x4ed3fe
    gopkg.in/BenLubar/espeak%2ev2.(*Context).synthesize(0xc4200aa080, 0x5415af, 0x45a, 0x0, 0x0)
            /home/jonhall/go/src/gopkg.in/BenLubar/espeak.v2/doc.go:335 +0x18e fp=0xc42005dbf0 sp=0xc42005dba8 pc=0x4eb30e
    gopkg.in/BenLubar/espeak%2ev2.(*Context).SynthesizeText(0xc4200aa080, 0x5415af, 0x45a, 0x429809, 0xc4200b4170)
            /home/jonhall/go/src/gopkg.in/BenLubar/espeak.v2/doc.go:308 +0x47 fp=0xc42005dc28 sp=0xc42005dbf0 pc=0x4eb127
    gopkg.in/BenLubar/espeak%2ev2_test.Example_ssml()
            /home/jonhall/go/src/gopkg.in/BenLubar/espeak.v2/example_test.go:34 +0x59 fp=0xc42005dc78 sp=0xc42005dc28 pc=0x4ee799
    testing.runExample(0x539d86, 0xc, 0x541b00, 0x0, 0x0, 0x0, 0x1)
            /usr/local/go/src/testing/example.go:122 +0x1f9 fp=0xc42005dd40 sp=0xc42005dc78 pc=0x4ad769
    testing.runExamples(0xc42005dee0, 0x7d52c0, 0x1, 0x1, 0x410100)
            /usr/local/go/src/testing/example.go:46 +0x15b fp=0xc42005de28 sp=0xc42005dd40 pc=0x4ad3cb
    testing.(*M).Run(0xc4200aa000, 0x0)
            /usr/local/go/src/testing/testing.go:979 +0x1eb fp=0xc42005df20 sp=0xc42005de28 pc=0x4b05eb
    main.main()
            _testmain.go:44 +0x151 fp=0xc42005df88 sp=0xc42005df20 pc=0x4eea51
    runtime.main()
            /usr/local/go/src/runtime/proc.go:198 +0x212 fp=0xc42005dfe0 sp=0xc42005df88 pc=0x42c562
    runtime.goexit()
            /usr/local/go/src/runtime/asm_amd64.s:2361 +0x1 fp=0xc42005dfe8 sp=0xc42005dfe0 pc=0x457111

    goroutine 6 [IO wait]:
    internal/poll.runtime_pollWait(0x7fd5dfb4fed0, 0x72, 0xc420039ce0)
            /usr/local/go/src/runtime/netpoll.go:173 +0x57
    internal/poll.(*pollDesc).wait(0xc4200901a8, 0x72, 0xffffffffffffff01, 0x551840, 0x7db978)
            /usr/local/go/src/internal/poll/fd_poll_runtime.go:85 +0x9b
    internal/poll.(*pollDesc).waitRead(0xc4200901a8, 0xc4200c4001, 0x200, 0x200)
            /usr/local/go/src/internal/poll/fd_poll_runtime.go:90 +0x3d
    internal/poll.(*FD).Read(0xc420090190, 0xc4200c4000, 0x200, 0x200, 0x0, 0x0, 0x0)
            /usr/local/go/src/internal/poll/fd_unix.go:157 +0x17d
    os.(*File).read(0xc42000e048, 0xc4200c4000, 0x200, 0x200, 0xc4200c4000, 0x0, 0x0)
            /usr/local/go/src/os/file_unix.go:226 +0x4e
    os.(*File).Read(0xc42000e048, 0xc4200c4000, 0x200, 0x200, 0x0, 0x0, 0xc420039e58)
            /usr/local/go/src/os/file.go:107 +0x6a
    bytes.(*Buffer).ReadFrom(0xc4200c0000, 0x551720, 0xc42000e048, 0x7fd5d831e020, 0xc4200c0000, 0x1000000453401)
            /usr/local/go/src/bytes/buffer.go:205 +0xa0
    io.copyBuffer(0x551620, 0xc4200c0000, 0x551720, 0xc42000e048, 0x0, 0x0, 0x0, 0x522a40, 0x1, 0xc4200c0000)
            /usr/local/go/src/io/io.go:386 +0x31a
    io.Copy(0x551620, 0xc4200c0000, 0x551720, 0xc42000e048, 0x0, 0xc42001e2f8, 0x4518d0)
            /usr/local/go/src/io/io.go:362 +0x5a
    testing.runExample.func1(0xc42000e048, 0xc42001e360)
            /usr/local/go/src/testing/example.go:76 +0x72
    created by testing.runExample
            /usr/local/go/src/testing/example.go:74 +0x155
    FAIL    gopkg.in/BenLubar/espeak.v2     0.078s

**Comment by BenLubar** [comment]
I can reproduce this with the version of espeak-ng in Debian's apt repository, but compiling https://github.com/espeak-ng/espeak-ng/releases/tag/1.49.2 from source did not exhibit this behavior.

**Comment by flimzy** [comment]
Thanks for testing and reporting a work-around. I'll use 1.49.2 as well, and consider this issue closed, since it's apparently unrelated to the Go library.
